In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time
import requests
import json
import sklearn 
from py_clob_client import ClobClient

import asyncio
import websockets

In [2]:
GAMMA_API = 'https://gamma-api.polymarket.com'
CLOB_API = 'https://clob.polymarket.com'

In [3]:
def get_current_btc_5m_token_ids():
    current_time = int(time.time())
    current_interval = (current_time // 300) * 300
    slug = f"btc-updown-5m-{current_interval}"
    url = f"{GAMMA_API}/markets"
    response = requests.get(url, params={'slug': slug}).json()
    token_ids = json.loads(response[0]['clobTokenIds']) # [yes_token_id, no_token_id]
    return token_ids

In [ ]:
current_time = int(time.time())
current_interval = (current_time // 300) * 300
slug = f"btc-updown-5m-{current_interval}"
url = f"{GAMMA_API}/markets"
response = requests.get(url, params={'slug': slug}).json()
token_ids = json.loads(response[0]['clobTokenIds'])
response

[{'id': '1528112',
  'question': 'Bitcoin Up or Down - March 8, 7:10PM-7:15PM ET',
  'conditionId': '0xbcf14dd29bcea4a05f24a83ca624ca3a2e7c2aba3fcb79cb07d233b72f3f0043',
  'slug': 'btc-updown-5m-1773011400',
  'resolutionSource': 'https://data.chain.link/streams/btc-usd',
  'endDate': '2026-03-08T23:15:00Z',
  'liquidity': '58616.0708',
  'startDate': '2026-03-07T23:18:25.341352Z',
  'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png',
  'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png',
  'description': 'This market will resolve to "Up" if the Bitcoin price at the end of the time range specified in the title is greater than or equal to the price at the beginning of that range. Otherwise, it will resolve to "Down".\nThe resolution source for this market is information from Chainlink, specifically the BTC/USD data stream available at https://data.chain.link/streams/btc-usd.\nPlease note that this market is about the price according to Chainlink data stream BTC/USD, not according to other sources or spot markets.',
  'outcomes': '["Up", "Down"]',
  'outcomePrices': '["0.505", "0.495"]',
  'volume': '812.6312780000001',
  'active': True,
  'closed': False,
  'marketMakerAddress': '',
  'createdAt': '2026-03-07T23:17:03.076444Z',
  'updatedAt': '2026-03-08T23:08:39.665947Z',
  'new': False,
  'featured': False,
  'archived': False,
  'restricted': True,
  'groupItemThreshold': '0',
  'questionID': '0xfecdd84779b9063e8db6ab1d6dfcd600cae75fed99939e5e11bb075598da2311',
  'enableOrderBook': True,
  'orderPriceMinTickSize': 0.01,
  'orderMinSize': 5,
  'volumeNum': 812.6312780000001,
  'liquidityNum': 58616.0708,
  'endDateIso': '2026-03-08',
  'startDateIso': '2026-03-07',
  'hasReviewedDates': True,
  'volume24hr': 864.8898170000002,
  'volume1wk': 864.8898170000002,
  'volume1mo': 864.8898170000002,
  'volume1yr': 864.8898170000002,
  'clobTokenIds': '["88808867545673970124225431271032752135195427267158312598672772673517062711153", "86851010783503819542527250915557714262353108152702136722840075498781748326175"]',
  'volume24hrClob': 864.8898170000002,
  'volume1wkClob': 864.8898170000002,
  'volume1moClob': 864.8898170000002,
  'volume1yrClob': 864.8898170000002,
  'volumeClob': 812.6312780000001,
  'liquidityClob': 58616.0708,
  'makerBaseFee': 1000,
  'takerBaseFee': 1000,
  'acceptingOrders': True,
  'negRisk': False,
  'events': [{'id': '252988',
    'ticker': 'btc-updown-5m-1773011400',
    'slug': 'btc-updown-5m-1773011400',
    'title': 'Bitcoin Up or Down - March 8, 7:10PM-7:15PM ET',
    'description': 'This market will resolve to "Up" if the Bitcoin price at the end of the time range specified in the title is greater than or equal to the price at the beginning of that range. Otherwise, it will resolve to "Down".\nThe resolution source for this market is information from Chainlink, specifically the BTC/USD data stream available at https://data.chain.link/streams/btc-usd.\nPlease note that this market is about the price according to Chainlink data stream BTC/USD, not according to other sources or spot markets.',
    'resolutionSource': 'https://data.chain.link/streams/btc-usd',
    'startDate': '2026-03-07T23:19:14.81711Z',
    'creationDate': '2026-03-07T23:19:14.817106Z',
    'endDate': '2026-03-08T23:15:00Z',
    'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png',
    'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png',
    'active': True,
    'closed': False,
    'archived': False,
    'new': False,
    'featured': False,
    'restricted': True,
    'liquidity': 58933.0328,
    'volume': 557.685283,
    'openInterest': 0,
    'createdAt': '2026-03-07T23:17:02.980851Z',
    'updatedAt': '2026-03-08T23:07:17.111365Z',
    'competitive': 0.9999750006249843,
    'volume24hr': 567.7049240000001,
    'volume1wk': 567.7049240000001,
    'volume1mo': 567.7049240000001,
    'volume1yr': 567.7049240000001,
    'enableOrderBook': True,
    'liquidityClob': 58933.0328,
    'negRisk': False,
    'commentCount': 0,
    'series': [{'id': '10684',
      'ticker': 'btc-up-or-down-5m',
      'slug': 'btc-up-or-down-5m',
      'title': 'BTC Up or Down 5m',
      'seriesType': 'single',
      'recurrence': '5m',
      'image': '',
      'icon': '',
      'active': True,
      'closed': False,
      'archived': False,
      'featured': False,
      'restricted': True,
      'createdAt': '2025-11-21T21:46:22.201627Z',
      'updatedAt': '2026-03-08T23:07:21.256389Z',
      'volume24hr': 40134418.169597976,
      'volume': 43191.89283600003,
      'liquidity': 5660971.632,
      'commentCount': 24159,
      'requiresTranslation': False}],
    'cyom': False,
    'showAllOutcomes': True,
    'showMarketImages': True,
    'enableNegRisk': False,
    'automaticallyActive': True,
    'startTime': '2026-03-08T23:10:00Z',
    'seriesSlug': 'btc-up-or-down-5m',
    'negRiskAugmented': False,
    'pendingDeployment': False,
    'deploying': False,
    'requiresTranslation': False}],
  'ready': False,
  'funded': False,
  'acceptingOrdersTimestamp': '2026-03-07T23:17:19Z',
  'cyom': False,
  'competitive': 0.9999750006249843,
  'pagerDutyNotificationEnabled': False,
  'approved': True,
  'rewardsMinSize': 50,
  'rewardsMaxSpread': 4.5,
  'spread': 0.008,
  'lastTradePrice': 0.51,
  'bestBid': 0.5,
  'bestAsk': 0.51,
  'automaticallyActive': True,
  'clearBookOnStart': False,
  'showGmpSeries': False,
  'showGmpOutcome': False,
  'manualActivation': False,
  'negRiskOther': False,
  'umaResolutionStatuses': '[]',
  'pendingDeployment': False,
  'deploying': False,
  'rfqEnabled': False,
  'eventStartTime': '2026-03-08T23:10:00Z',
  'holdingRewardsEnabled': False,
  'feesEnabled': True,
  'requiresTranslation': False,
  'makerRebatesFeeShareBps': 10000,
  'feeType': 'crypto_fees'}]

:

In [4]:
res = requests.get(CLOB_API + "/book", params={'token_id': get_current_btc_5m_token_ids()[0]}).json()
res

{'market': '0x2ecd9ef38c8cb85a8d536ef9281e544a468aa736e206206b2733fbfeaeb0b70f',
 'asset_id': '61531504470806867051166853062521973894399040607534267534855476296587465270849',
 'timestamp': '1773000362770',
 'hash': '1a3298bbd439ad56c41c80e0d1db4f66f21fa37a',
 'bids': [{'price': '0.01', 'size': '30266.47'},
  {'price': '0.02', 'size': '10049.16'},
  {'price': '0.03', 'size': '2811.49'},
  {'price': '0.04', 'size': '2883.75'},
  {'price': '0.05', 'size': '1175.83'},
  {'price': '0.06', 'size': '1336.65'},
  {'price': '0.07', 'size': '1662.4'},
  {'price': '0.08', 'size': '685.43'},
  {'price': '0.09', 'size': '280'},
  {'price': '0.1', 'size': '724'},
  {'price': '0.11', 'size': '971.29'},
  {'price': '0.12', 'size': '491.42'},
  {'price': '0.13', 'size': '158.32'},
  {'price': '0.14', 'size': '593.14'},
  {'price': '0.15', 'size': '195.32'},
  {'price': '0.16', 'size': '397.8'},
  {'price': '0.17', 'size': '508.88'},
  {'price': '0.18', 'size': '139.55'},
  {'price': '0.19', 'size': '229.26'},
  {'price': '0.2', 'size': '259'},
  {'price': '0.21', 'size': '700'},
  {'price': '0.22', 'size': '254'},
  {'price': '0.23', 'size': '285.01'},
  {'price': '0.24', 'size': '749'},
  {'price': '0.25', 'size': '228.14'},
  {'price': '0.26', 'size': '411'},
  {'price': '0.27', 'size': '267'},
  {'price': '0.28', 'size': '262.28'},
  {'price': '0.29', 'size': '386'},
  {'price': '0.3', 'size': '2360.08'},
  {'price': '0.31', 'size': '277.05'},
  {'price': '0.32', 'size': '105'},
  {'price': '0.33', 'size': '268.25'},
  {'price': '0.34', 'size': '42.75'}],
 'asks': [{'price': '0.99', 'size': '29881.46'},
  {'price': '0.98', 'size': '10974.5'},
  {'price': '0.97', 'size': '2928.15'},
  {'price': '0.96', 'size': '2791.75'},
  {'price': '0.95', 'size': '1216'},
  {'price': '0.94', 'size': '1336.65'},
  {'price': '0.93', 'size': '1306'},
  {'price': '0.92', 'size': '640'},
  {'price': '0.91', 'size': '280'},
  {'price': '0.9', 'size': '784'},
  {'price': '0.89', 'size': '839.29'},
  {'price': '0.88', 'size': '491.42'},
  {'price': '0.87', 'size': '163.32'},
  {'price': '0.86', 'size': '593.14'},
  {'price': '0.85', 'size': '155.32'},
  {'price': '0.84', 'size': '392.25'},
  {'price': '0.83', 'size': '519.88'},
  {'price': '0.82', 'size': '130.55'},
  {'price': '0.81', 'size': '135.26'},
  {'price': '0.8', 'size': '175'},
  {'price': '0.79', 'size': '611'},
  {'price': '0.78', 'size': '158'},
  {'price': '0.77', 'size': '125'},
  {'price': '0.76', 'size': '125'},
  {'price': '0.75', 'size': '135.2'},
  {'price': '0.74', 'size': '364'},
  {'price': '0.73', 'size': '125'},
  {'price': '0.72', 'size': '142'},
  {'price': '0.71', 'size': '206'},
  {'price': '0.7', 'size': '899.15'},
  {'price': '0.69', 'size': '226'},
  {'price': '0.68', 'size': '237.14'},
  {'price': '0.67', 'size': '331.2'},
  {'price': '0.66', 'size': '270.18'},
  {'price': '0.65', 'size': '321.96'},
  {'price': '0.64', 'size': '331.7'},
  {'price': '0.63', 'size': '292'},
  {'price': '0.62', 'size': '242'},
  {'price': '0.61', 'size': '242'},
  {'price': '0.6', 'size': '284'},
  {'price': '0.59', 'size': '242'},
  {'price': '0.58', 'size': '250.09'},
  {'price': '0.57', 'size': '255.47'},
  {'price': '0.56', 'size': '280'},
  {'price': '0.55', 'size': '312'},
  {'price': '0.54', 'size': '296'},
  {'price': '0.53', 'size': '116'},
  {'price': '0.52', 'size': '631'},
  {'price': '0.51', 'size': '301.88'},
  {'price': '0.5', 'size': '203.66'},
  {'price': '0.49', 'size': '160.83'},
  {'price': '0.48', 'size': '182.26'},
  {'price': '0.47', 'size': '167'},
  {'price': '0.46', 'size': '250'},
  {'price': '0.45', 'size': '296'},
  {'price': '0.44', 'size': '290.68'},
  {'price': '0.43', 'size': '325'},
  {'price': '0.42', 'size': '341.1'},
  {'price': '0.41', 'size': '384.64'},
  {'price': '0.4', 'size': '488.42'},
  {'price': '0.39', 'size': '896.85'},
  {'price': '0.38', 'size': '275.72'},
  {'price': '0.37', 'size': '148'},
  {'price': '0.36', 'size': '5.9'}],
 'min_order_size': '5',
 'tick_size': '0.01',
 'neg_risk': False,
 'last_trade_price': '0.340'}

In [5]:
data = pd.read_parquet('data/polymarket_orderbook_2026-03-08T18.parquet')

In [35]:
filters = [
    ('market_id', '=', '0x592c4a829557baa652fea1ff6d94bdbe97da961e58d30155114a032390621992'),
    # ('update_type', 'in', ['book_snapshot', 'price_change'])
]
data = pd.read_parquet('data/polymarket_orderbook_2026-03-08T18.parquet',
                       filters=filters)

In [50]:
data.sort_values('timestamp_received')

,timestamp_received,timestamp_created_at,market_id,update_type,data
122,2026-03-08 18:00:06.499000+00:00,2026-03-08 18:00:06.550000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."
123,2026-03-08 18:00:06.499000+00:00,2026-03-08 18:00:06.550000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."
124,2026-03-08 18:00:08.341000+00:00,2026-03-08 18:00:08.383000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."
125,2026-03-08 18:00:08.341000+00:00,2026-03-08 18:00:08.383000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."
127,2026-03-08 18:02:34.039000+00:00,2026-03-08 18:02:34.084000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."
...,...,...,...,...,...
117,2026-03-08 18:59:57.970000+00:00,2026-03-08 18:59:58.007000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."
118,2026-03-08 18:59:58.049000+00:00,2026-03-08 18:59:58.110000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."
119,2026-03-08 18:59:58.049000+00:00,2026-03-08 18:59:58.110000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."
120,2026-03-08 18:59:58.127000+00:00,2026-03-08 18:59:58.175000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."
121,2026-03-08 18:59:58.127000+00:00,2026-03-08 18:59:58.175000+00:00,0x592c4a829557baa652fea1ff6d94bdbe97da961e58d3...,price_change,"{""update_type"": ""price_change"", ""market_id"": ""..."

In [66]:
book_snapshot = data.query('update_type == "book_snapshot"').iloc[1]['data']
book_snapshot = json.loads(book_snapshot)

In [80]:
bids_snapshot = pd.DataFrame(book_snapshot['bids'], columns=['price', 'size'], dtype=float).sort_values('price', ascending=False)
asks_snapshot = pd.DataFrame(book_snapshot['asks'], columns=['price', 'size'], dtype=float)
asks_snapshot['price'] = pd.to_numeric(asks_snapshot['price'])
asks_snapshot['size'] = pd.to_numeric(asks_snapshot['size'])
bids_snapshot['price'] = pd.to_numeric(bids_snapshot['price'])
bids_snapshot['size'] = pd.to_numeric(bids_snapshot['size'])

# Feature extraction:

In [ ]:
def get_volume_at_price_level(book_snapshot, price_level):
    # Assumes book_snapshot is already sorted by price level, with asks in 
    # ascending order and bids in descending order
    level_idx = min(price_level, len(book_snapshot))
    volume = book_snapshot.iloc[:level_idx]['size'].sum()
    return volume

def get_order_imbalance_at_price_level(bids_snapshot, asks_snapshot, price_level):
    bid_volume = get_volume_at_price_level(bids_snapshot, price_level)
    ask_volume = get_volume_at_price_level(asks_snapshot, price_level)
    imbalance = (bid_volume - ask_volume) / (bid_volume + ask_volume) if (bid_volume + ask_volume) > 0 else 0
    return imbalance

get_volume_at_price_level(bids_snapshot, 5)

np.float64(4829.63)

In [82]:
bids_snapshot

    price      size
40   0.49   1085.63
39   0.48    907.00
38   0.47   1015.00
37   0.46    791.00
36   0.45   1031.00
35   0.44    789.00
34   0.43   1236.00
33   0.42    982.00
32   0.41   1261.00
31   0.40   1161.00
30   0.39    504.00
29   0.38   1206.00
28   0.37    480.00
27   0.36   1266.00
26   0.35    225.00
25   0.34    225.00
24   0.33   1455.00
23   0.32    325.00
22   0.31    225.00
21   0.30   1375.00
20   0.29      5.80
19   0.28    200.00
18   0.26    405.00
17   0.25   1205.00
16   0.24   1000.00
15   0.21      5.21
14   0.20   1725.00
13   0.16      5.19
12   0.15   2300.00
11   0.12      6.33
10   0.11     35.00
9    0.10   3360.00
8    0.09      7.03
7    0.08     20.00
6    0.07     70.49
5    0.06    256.65
4    0.05    645.66
3    0.04    853.81
2    0.03  11277.99
1    0.02   3834.41
0    0.01  12511.05

In [21]:
sample_msg = {
  "event_type": "book",
  "asset_id": "65818619657568813474341868652308942079804919287380422192892211131408793125422",
  "market": "0xbd31dc8a20211944f6b70f31557f1001557b59905b7738480ca09bd4532f84af",
  "bids": [
    { "price": ".48", "size": "30" },
    { "price": ".49", "size": "20" },
    { "price": ".50", "size": "15" }
  ],
  "asks": [
    { "price": ".52", "size": "25" },
    { "price": ".53", "size": "60" },
    { "price": ".54", "size": "10" }
  ],
  "timestamp": "123456789000",
  "hash": "0x0...."
}

prx_change = {
  "market": "0x5f65177b394277fd294cd75650044e32ba009a95022d88a0c1d565897d72f8f1",
  "price_changes": [
    {
      "asset_id": "71321045679252212594626385532706912750332728571942532289631379312455583992563",
      "price": "0.5",
      "size": "200",
      "side": "BUY",
      "hash": "56621a121a47ed9333273e21c83b660cff37ae50",
      "best_bid": "0.5",
      "best_ask": "1"
    }
  ],
  "timestamp": "1757908892351",
  "event_type": "price_change"
}

bids_snapshot = pd.DataFrame(sample_msg['bids'], columns=['price', 'size'], dtype=np.float32).sort_values('price', ascending=False)
bids_snapshot['timestamp'] = int(sample_msg['timestamp'])
bids_snapshot['market_id'] = sample_msg['market']

asks_snapshot = pd.DataFrame(sample_msg['asks'], columns=['price', 'size'], dtype=np.float32)
asks_snapshot['timestamp'] = int(sample_msg['timestamp'])
asks_snapshot['market_id'] = sample_msg['market']

In [23]:
bids_snapshot.loc[bids_snapshot['price'] == float('0.5'), 'size'] = 200

In [24]:
bids_snapshot

,price,size,timestamp,market_id
2,0.50,200.0,123456789000,0xbd31dc8a20211944f6b70f31557f1001557b59905b77...
1,0.49,20.0,123456789000,0xbd31dc8a20211944f6b70f31557f1001557b59905b77...
0,0.48,30.0,123456789000,0xbd31dc8a20211944f6b70f31557f1001557b59905b77...

In [6]:
asks_snapshot

   price  size
0   0.52  25.0
1   0.53  60.0
2   0.54  10.0

In [ ]:
df = pd.read_pickle('raw_book_data/book-btc-updown-5m-1773077700.pkl')

In [27]:
df['market_id'].unique()

array(['0x957963f85e7dd3409ef7fc3a91e15de110f7ea5f069bcbdb038208e7afbcc1eb',
       '0xfacb328ed8da84b7ed68981c16ab043db704d48decc9079b93f774d3136d656b'],
      dtype=object)